version: "3.1"
services:
  gateway-api:
    networks:
      vicinity:
#        ipv4_address: 10.6.0.5 
    volumes:
    - ./logs/gateway-dev:/gateway/log
    - ./configuration/GatewayConfig.xml:/gateway/config/GatewayConfig.xml:rw
    container_name: vicinity-gateway-api
    ports:
    - 8181:8181
    #image: gtw-api:latest
    image: bavenir/vicinity-gateway-api:latest
  device-dummy:
    networks:
      vicinity:
#        ipv4_address: 10.6.0.10
    volumes:
    - ./logs/dev-logs:/home/app/logs
    - ./agent:/home/app/agent
    - ./vas.config.js:/home/app/vas.config.js:rw
    container_name: vicinity-dummy-device
    ports:
    - 9997:9997
    image: bavenir/vicinity-dummy-device:dev
networks:
  vicinity:
    driver: bridge
#    ipam:
#      config:
#      - subnet: 10.6.0.0/16
